### ISSUE TITLE
Firmware Update Error

### ISSUE THREAD

**Issue by vmalepati1** [DcentWallet/dcent-cli-connector#2]
Hello,

When calling the getAccountInfo() function, I am getting the following error:

`error: { code: 'not_support', message: 'You need to firmware update' }`

Even though my wallet has been updated to firmware version 2.25.1.66ca.

The wallet is plugged in and when calling info(), I get the following successful response:
```
{
  header: { version: '1.0', request_from: 'dcent-cli', status: 'success' },
  body: { command: 'info', parameter: { isUsbAttached: true } }
}
```

**Comment by kekim-iotrust** [comment]
@vmalepati1 

Hello, 
Thanks for your interest in dcent-cli-connect.

There is a sample code in dcent-cli-connector.
`sample/index.js`
Please refer to the sample code.

You can run the sample code
```
node sample/index.js
```

**Comment by vmalepati1** [comment]
@KyungeunKim 

Thank you very much for the reference, the sample code fixed the firmware issue but now I have another issue here: #3
